<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>lt.ktu.paskutinisatsiskaitymas</groupId>
    <artifactId>paskutinis-atsiskaitymas</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>
  <artifactId>game-domain</artifactId>
  <properties>
    <forbidden.imports>^(?!java\.|lt\.ktu\.paskutinisatsiskaitymas\.domain(?:\.|$)).*,^java\.(awt|net|sql)\..*</forbidden.imports>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <finalName>game-domain</finalName>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <executions>
          <execution>
            <id>module-dependencies</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <bannedDependencies>
                  <excludes>
                    <exclude>lt.ktu.paskutinisatsiskaitymas:*</exclude>
                  </excludes>
                  <includes/>
                </bannedDependencies>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
